package pbft

const (
	GLOBAL_APPLICATION = "GLOBAL_PBFT"
	APPLICATION = "APP_PBFT"
	NATS_PBFT_INBOX = "NATS_PBFT_INBOX"

	NEW_MESSAGE = "NEW_MESSAGE"
	PRE_PREPARE = "PRE_PREPARE"
	PREPARE = "PREPARE"
	COMMIT = "COMMIT"
	COMMITED = "COMMITED"
)
