package pbft

const (
	GLOBAL_APPLICATION = "GLOBAL_PBFT"
	APPLICATION        = "APP_PBFT"
	NATS_PBFT_INBOX    = "NATS_PBFT_INBOX"
	LOCAL              = "LOCAL_TXN"
	LOCAL_CONSENSUS    = "LOCAL_CONSENSUS"
	GLOBAL             = "GLOBAL_TXN"

	TIMEOUT     = 4
	NEW_MESSAGE = "NEW_MESSAGE"
	PRE_PREPARE = "PRE_PREPARE"
	VIEW_CHANGE = "VIEW_CHANGE"
	NEW_VIEW    = "NEW_VIEW"
	PREPARE     = "PREPARE"
	COMMIT      = "COMMIT"
	COMMITED    = "COMMITED"
)
