package pbftSingleLayer

const (
	GLOBAL_APPLICATION = "GLOBAL_SLPBFT"
	GLOBAL             = "GLOBAL_TXN"

	TIMEOUT     = 4
	NEW_MESSAGE = "NEW_MESSAGE"
	PRE_PREPARE = "PRE_PREPARE"
	VIEW_CHANGE = "VIEW_CHANGE"
	NEW_VIEW    = "NEW_VIEW"
	PREPARE     = "PREPARE"
	COMMIT      = "COMMIT"
	COMMITED    = "COMMITED"
)
