package common

const (
	INTERNAL_TXN  = "INTERNAL_TXN"
	CROSS_APP_TXN = "CROSS_APPLICATION_TXN"

	TXN_ID = "TXN-%s-%s"

	// Message Types
	REQUEST = "REQUEST"
	ORDER   = "ORDER"
	SYNC    = "SYNC"

	// NATS inbox messages
	// ORDERER MESSAGES
	NATS_ORD_REQUEST = "NATS_ORDERER_REQUEST"
	NATS_ORD_ORDER   = "NATS_ORDERER_ORDER"
	NATS_ORD_SYNC    = "NATS_ORDERER_SYNC"
)
