FROM alpine:3.3
ARG nodeID
ARG basedir
ARG configdir

RUN mkdir /orderer/

COPY $basedir/bin/orderers /orderer

WORKDIR /orderer

EXPOSE 8080

ENTRYPOINT ["/orderer/orderers", "--nodeID", "${nodeID}", "--configFilePath", "${basedir}/config.json"] 